aboutme/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index),
]

contacts/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index),
]

faq/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index),
]

home/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index),
]

register/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index),
]

schedule/urls.py
from django.urls import path
from . import views
from .views import index, addschedule, saveschedule

app_name = 'schedule'
urlpatterns = [
    path('', views.index, name='index'),
    path('addschedule/', views.addschedule, name='addschedule'),
    path('saveschedule/', views.saveschedule, name='saveschedule'),
    path('deleteschedule/', views.deleteschedule, name='deleteschedule')
]

story/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('aboutme/', include('aboutme.urls')),
    path('faq/', include('faq.urls')),
    path('contacts/', include('contacts.urls')),
    path('register/', include('register.urls')),
    path('schedule/', include('schedule.urls', namespace='schedule')),
]

aboutme/models.py
from django.db import models

# Create your models here.

contacts/models.py
from django.db import models

# Create your models here.

faq/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

register/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models

class Schedule(models.Model):
	activity = models.CharField(max_length=25)
	category = models.CharField(max_length=20)
	place = models.CharField(max_length=20)
	date = models.DateField()
	time = models.TimeField()

schedule/forms.py
from django import forms
from .models import Schedule

class ScheduleForm(forms.ModelForm):
    activity = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Please fill out activity name'}))
    category = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Please fill out category name'}))
    place = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Please fill out place name'}))
    date = forms.DateField(widget=forms.DateInput(attrs={'class' : 'form-control', 'type' : 'date'}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={'class' : 'form-control', 'type' : 'time'}))

    class Meta:
        model = Schedule
        fields = ('activity','category', 'place', 'date', 'time')
        fiels_required = ('activity', 'category', 'place', 'date', 'time')

aboutme/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'aboutme.html')

contacts/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'contacts.html')

faq/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'faq.html')

home/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'homepage.html')

register/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'register.html')

schedule/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import ScheduleForm
from .models import Schedule

response = {}

def index(request):
    schedule = Schedule.objects.all().order_by('date', 'time')
    response['schedule'] = schedule
    html = 'schedule.html'
    print(response)
    return render(request, html, response)

def addschedule(request):
    response['form'] = ScheduleForm
    html = 'addschedule.html'
    return render(request, html, response)

def saveschedule(request):
    form = ScheduleForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['activity'] = request.POST['activity']
        response['category'] = request.POST['category']
        response['place'] = request.POST['place']
        response['date'] = request.POST['date']
        response['time'] = request.POST['time']
        schedule = Schedule(activity=response['activity'], category=response['category'], place=response['place'],
                            date=response['date'], time=response['time'])
        schedule.save()
        return HttpResponseRedirect('/../schedule')
    else:
        return HttpResponseRedirect('/../schedule/addschedule')

def deleteschedule(request):
    schedule = Schedule.objects.all().delete()
    response['schedule'] = schedule
    html = 'schedule.html'
    return HttpResponseRedirect('/../schedule')

aboutme/templates/aboutme.html
{% extends 'base.html' %}

{% block content %}
    <div class="content">
        <div class="page-title" id="top-title">About Me</div>
        <div class="page-box">
        	<div class="container-fluid">
                <div class="row" id="me-row">
                    <div class="col">
                        <ul class="bullet-text">
			            	<li>Born in Pekanbaru, July 22nd 1999</li>
			            	<li>I really love cats</li>
			            	<li>I'm a patient person</li>
			            </ul>
			        </div>
			        <div class="col">
                        <ul class="bullet-text">
			            	<li></li>
			            	<li></li>
			            	<li></li>
			            </ul>
			        </div>
			    </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="page-title">Skills</div>
        <div class="page-box" id="darker-box">
        	<div class="container-fluid">
                <div class="row" id="me-row">
                    <div class="col">
                        <ul class="bullet-text">
			            	<li>Excels in Adobe Illustrator</li>
			            	<li>Excels in Paint Tool SAI</li>
			            	<li>Excels in Python and Java</li>
			            </ul>
			        </div>
			        <div class="col">
                        <ul class="bullet-text">
			            	<li></li>
			            	<li></li>
			            	<li></li>
			            </ul>
			        </div>
			    </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="page-title">Achievements</div>
        <div class="page-box">
        	<div class="container-fluid">
                <div class="row" id="me-row">
                    <div class="col">
                        <ul class="bullet-text">
			            	<li>Ranked 10th in province tryout of national exam</li>
			            	<li></li>
			            	<li></li>
			            </ul>
			        </div>
			        <div class="col">
                        <ul class="bullet-text">
			            	<li></li>
			            	<li></li>
			            	<li></li>
			            </ul>
			        </div>
			    </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="page-title">Experiences</div>
        <div class="page-box" id="darker-box">
        	<div class="last-box">
            	<div class="container-fluid">
                    <div class="row" id="me-row">
                        <div class="col">
                            <ul class="bullet-text">
				            	<li>Design & Creative in BETIS 2017</li>
				            	<li>Design & Creative in SIWAK 2018</li>
				            	<li>Academic Division in PMB 2018</li>
				            </ul>
				        </div>
				        <div class="col">
                            <ul class="bullet-text">
				            	<li></li>
				            	<li></li>
				            	<li></li>
				            </ul>
				        </div>
				    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

contacts/templates/contacts.html
{% extends 'base.html' %}

{% block content %}
    <div class="page-title" id="top-title">Contacts</div>
        <div class="page-box">
            <div class="container-fluid">
                <div class="row" id="contact-row1">
                    <i class="fa fa-whatsapp" id="wa"></i>
                    <div class="col">087863224506</div>
                    <i class="fa fa-envelope" id="email"></i>
                    <div class="col"">alya.zahra71@ui.ac.id</div>
                </div>
                <div class="row" id="contact-row2">
                    <i class="fa fa-gitlab" id="gitlab"></i>
                    <div class="col">alzahra</div>
                    <i class="fa fa-instagram" id="insta"></i>
                    <div class="col">alyazahra22</div>
                </div>
            </div>
        </div>
{% endblock %}

faq/templates/faq.html
{% extends 'base.html' %}

{% block content %}
    <div class="page-title" id="top-title">
    	Frequently Asked
    	<br>Questions</br>
    </div>
    <div class="container-fluid">
        <div class="row" id="faq-row">
            <div class="col">
            	<div class="question">1. What's your favorite activity?</div>
            	<div class="answer">I love drawing.</div>
            </div>
            
            <div class="col">
            	<div class="question">2. Python or Java?</div>
            	<div class="answer">Java for sure.</div>
            </div>
        </div>
       	<div class="row" id="faq-row">
            <div class="col">
            	<div class="question">3.</div>
            	<div class="answer"></div>
            </div>
            
            <div class="col">
            	<div class="question">4.</div>
            	<div class="answer"></div>
            </div>
        </div>
        <div class="row" id="lastfaq-row">
            <div class="col">
            	<div class="question">5.</div>
            	<div class="answer"></div>
            </div>
            
            <div class="col">
            	<div class="question">6.</div>
            	<div class="answer"></div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        {% load static %}
        <link rel='stylesheet' type='text/css' href="{% static "css/my-site.css" %}">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="home">
            <div class="container-fluid">
                <div class="home-title">Hello there, I'm Aya.</div>
                <div class="home-photo">
                    {% load static %}
                    <img src="{% static "img/me.jpg" %}" class="photo">
                </div>
                <div class="links">
                    <div class="homelink" id="about-me"><a href="..\aboutme">About Me</a></div>
                    <div class="homelink" id="faq"><a href="..\faq">F.A.Q</div>
                    <div class="homelink" id="contact"><a href="..\contacts">Contacts</div>
                    <div class="homelink" id="signup"><a href="..\register">Register</div>
                    <div class="homelink" id="schedule"><a href="..\schedule">Schedule</div>
                </div>
            </div>
        </div>
    </body>
</html>

register/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="page-title" id="top-title">Register Account</div>
    	<div class="page-box">
    		<div class="container mt-3">
    			<form action="#">
				    <div class="input-group mb-3">
				      	<input type="text" class="form-control" placeholder="Full Name" id="name">
				    </div>
				    <div class="input-group mb-3">
				      	<input type="date" class="form-control" placeholder="Date of Birth" id="date-of-birth">
				    </div>
				    <div class="input-group mb-3">
				      	<input type="email" class="form-control" placeholder="E-mail" id="e-mail">
				    </div>
				    <div class="input-group mb-3">
				      	<input type="text" class="form-control" placeholder="Username" id="username">
				    </div>
				    <div class="input-group mb-3">
				      	<input type="password" class="form-control" placeholder="Password" id="pass">
				    </div>
				    <div class="input-group mb-3">
				      	<input type="password" class="form-control" placeholder="Confirm Password" id="confirm-pass">
				    </div>
				    <button type="submit" class="btn btn-primary" id="submit-btn">Submit</button>
				</form>
    		</div>
    	</div>
{% endblock %}

schedule/templates/addschedule.html
{% extends 'base.html' %}

{% block content %}
    <div class="page-title" id="top-title">My Schedule</div>
        <div class="page-box">
            <form method="POST" class="form-post" action="{%url 'schedule:saveschedule' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" formmethod="POST" formaction="{%url 'schedule:saveschedule' %}" class="save btn btn-primary">Add Schedule</button>
            </form>
        </div>
{% endblock %}

schedule/templates/schedule.html
{% extends 'base.html' %}

{% block content %}
    <div class="page-title" id="top-title">My Schedule</div>
        <div class="page-box">
            <div class="cont">
                {% if schedule %}
                    <div class="table-responsive table-bordered">
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Activity</th>
                                    <th>Category</th>
                                    <th>Place</th>
                                    <th>Day</th>
                                    <th>Date</th>
                                    <th>Time</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for data in schedule %}
                                    <tr>
                                        <td>{{ data.activity }}</td>
                                        <td>{{ data.category }}</td>
                                        <td>{{ data.place }}</td>
                                        <td>{{ data.date|date:"l" }}</td>
                                        <td>{{ data.date }}</td>
                                        <td>{{ data.time }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <button class="save btn btn-primary" id="add-sch"><a href="{% url 'schedule:addschedule' %}">Add Schedule</a></button>
                    <button class="save btn btn-danger" id="dlt-sch"><a href="{% url 'schedule:deleteschedule' %}">Delete All</a></button>
                {% else %}
                    <div class="no-event">You have no activity</div>
                    <button class="save btn btn-primary" id="add-sch"><a href="{% url 'schedule:addschedule' %}">Add Schedule</a></button>
                {% endif %}
            </div>
        </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        
        <link rel='stylesheet' type='text/css' href="{% static "css/my-site.css" %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    </head>
    <body>
    	<div class="top-page">
            <nav class="navbar navbar-expand-sm navbar-light fixed-top">
            	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            		<span class="navbar-toggler-icon"></span>
            	</button>
            	<div class="collapse navbar-collapse" id="collapsibleNavbar">
	                <ul class="navbar-nav">
	                    <li class="nav-item"><a class="nav-link" href="\home">Home</a></li>
	                    <li class="nav-item"><a class="nav-link" href="\aboutme">About Me</a></li>
	                    <li class="nav-item"><a class="nav-link" href="\faq">F.A.Q</a></li>
	                    <li class="nav-item"><a class="nav-link" href="\contacts">Contacts</a></li>
	                    <li class="nav-item"><a class="nav-link" href="\register">Register</a></li>
                        <li class="nav-item"><a class="nav-link" href="\schedule">Schedule</a></li>
	                </ul>
	            </div>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>